# Generated by Django 2.2.7 on 2020-11-13 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Makanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_makanan', models.CharField(max_length=100)),
                ('kategori', models.CharField(choices=[('Makanan Barat', 'Makanan Barat'), ('Makanan Asia', 'Makanan Asia'), ('Makanan Indonesia', 'Makanan Indonesia'), ('Makanan Korea', 'Makanan Korea')], max_length=40)),
                ('gambar', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Bahan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bahan', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('satuan', models.CharField(choices=[('gr', 'gr'), ('buah', 'buah'), ('ml', 'ml')], max_length=10)),
                ('makanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resepmakanan.Makanan')),
            ],
        ),
    ]
